### ISSUE TITLE
Migration dependencies are not satisfied if catalogue app have been forked

### ISSUE THREAD

**Issue by marangonico** [django-oscar/django-oscar-promotions#4]
Trying to update a django-oscar project from v1.6.x to v2, I have this problem.

The catalogue app has been forked and migrations name diverged, then migrations dependencies check fails with the following error:
`django.db.migrations.exceptions.NodeNotFoundError: Migration oscar_promotions.0001_initial dependencies reference nonexistent parent node ('catalogue', '0013_auto_20170821_1548')`

**Comment by solarissmoke** [comment]
This is a fairly common problem with apps that share dependencies. We will need to look at whether the promotions app really needs to have that dependency, but in the mean time I'd suggest the simplest solution is for you to create an empty migration named `0013_auto_20170821_1548` in your forked app, so that the dependency resolution works.

**Comment by marangonico** [comment]
Thank you.

**Comment by solarissmoke** [comment]
I don't think there is a way to fix this here - the way Oscar's app forking works means this sort of thing is always an issue. The solution is to do what I've suggested above - i.e., to create an empty migration that has the same name as the one being targeted.

**Comment by vzgopro1** [comment]
@solarissmoke Thank you, helped me very much!
